# Generated by Django 5.1.5 on 2025-05-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoo",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
